### ISSUE TITLE
Are the commands packed into ./bb able to access each other? Like Busybox does?

### ISSUE THREAD

**Issue by xplshn** [u-root/gobusybox#120]
Just a question: Does this work like Busybox, where for example, if you compile the `ASH` or `HUSH` shell and enable this behavior it will always use `Busybox` applets if they're there and lastly try looking at the PATH. Is it the same for `makebb` generated binaries? Is this planned?

**Comment by xplshn** [comment]
Ah, okay then. I thought that `bb` worked like `busybox`, where `busybox` applets would always try to use other `applets` instead of external commands. They query `$PATH` as the last resort. When running `cal` for example on `busybox ash` it will try to use `busybox's cal` and if it isn't packed as an applet, it will try to find it in the `$PATH` as a last resort.

**Comment by hugelgupf** [comment]
I think implementing that here would be pretty hard since we can ingest any
Go program, but can't hook into those program's exec calls easily. I can
think of a few ways but none of them are worth the complexity to be honest.

**Comment by xplshn** [comment]
Thanks for answering my question. Have a good rest of your day!
