### ISSUE TITLE
elaborate on constraints

### ISSUE THREAD

**Issue by orangecms** [u-root/gobusybox#24]
Just playing around a bit with `makebb` to see what it does. Here's one point where I'm somewhat confused: For the experiment, I created a subdirectory in gobusybox' root dir, and in that, initialized a module, and `go get -u`ed a single package, then told `makebb` to bb it up. Specifically, starting from said directory:

```sh
 ~/P/gobusybox/more-tests $ go mod init guiuiui
go: creating new go.mod: module guiuiui
 ~/P/gobusybox/more-tests $ go get -u gioui.org/example/kitchen
go: downloading gioui.org/example v0.0.0-20200829162755-829ee4559c5a
go: downloading gioui.org v0.0.0-20200829162755-829ee4559c5a
go: found gioui.org/example/kitchen in gioui.org/example v0.0.0-20200829162755-829ee4559c5a
go: downloading gioui.org v0.0.0-20200726090130-3b95e2918359
go: downloading golang.org/x/image v0.0.0-20200618115811-c13761719519
go: downloading golang.org/x/exp v0.0.0-20191002040644-a1355ae1e2c3
...
```

Go doing its thing, after that, this was `go.mod`:

```
module guiuiui

go 1.15

require (
        gioui.org v0.0.0-20200829162755-829ee4559c5a // indirect
        gioui.org/example v0.0.0-20200829162755-829ee4559c5a // indirect
        golang.org/x/exp v0.0.0-20200908183739-ae8ad444f925 // indirect
        golang.org/x/image v0.0.0-20200801110659-972c09e46d76 // indirect
        golang.org/x/sys v0.0.0-20200909081042-eff7692f9009 // indirect
        golang.org/x/text v0.3.3 // indirect
)
```

So I ran `makebb`:
```sh
~/P/gobusybox/ more-tests $ ../src/cmd/makebb/makebb gioui.org/example/kitchen
2020/09/11 20:48:19 Disabling CGO for u-root...
2020/09/11 20:48:19 Build environment: GOARCH=amd64 GOOS=linux GOPATH=/home/dan/go CGO_ENABLED=0 GO111MODULE= GOROOT=/usr/lib/go PATH=/usr/lib/go/bin:$PATH
2020/09/11 20:48:34 Preserving bb generated source directory at /tmp/bb-598536552 due to error
2020/09/11 20:48:34 go build: error building go package in "/tmp/bb-598536552/src/bb.u-root.com/bb": go: found gioui.org/example/kitchen in gioui.org/example v0.0.0-00010101000000-000000000000
package bb.u-root.com/bb
        imports gioui.org/example/kitchen
        imports gioui.org/app
        imports gioui.org/app/internal/window
        imports gioui.org/app/internal/egl
        imports gioui.org/app/internal/glimpl: build constraints exclude all Go files in /home/dan/go/pkg/mod/gioui.org@v0.0.0-20200726090130-3b95e2918359/app/internal/glimpl
, exit status 1
```

Clueless as I was, I tried turning `GO111MODULE` off:
 ```sh
~/P/gobusybox/ more-tests $ GO111MODULE=off ../src/cmd/makebb/makebb gioui.org/example/kitchen
2020/09/11 21:00:37 Disabling CGO for u-root...
2020/09/11 21:00:37 Build environment: GOARCH=amd64 GOOS=linux GOPATH=/home/dan/go CGO_ENABLED=0 GO111MODULE=off GOROOT=/usr/lib/go PATH=/usr/lib/go/bin:$PATH
2020/09/11 21:00:37 Skipping package gioui.org/example/kitchen for errors:
-: cannot find package "gioui.org/example/kitchen" in any of:
        /usr/lib/go/src/gioui.org/example/kitchen (from $GOROOT)
        /home/dan/go/src/gioui.org/example/kitchen (from $GOPATH)
2020/09/11 21:00:37 Preserving bb generated source directory at /tmp/bb-238598199 due to error
2020/09/11 21:00:37 no commands compiled
```

What are those constraints, how are they set, and how can I influence them? Can `makebb` provide some more information on that? I have no idea, but it's fun to play with this. :)

**Comment by hugelgupf** [comment]
Hey,

at the moment, there are two things here to be aware of -- I should elaborate on those in the README.

1. gobusybox, just like u-root, does not support cgo at the moment.

2. I've primarily been testing by cloning git repos, and passing local file system directory paths. What you did seems to work, and I got the same error when I cloned the repo and built locally, but just wanted you to be aware.

gioui depends heavily on cgo, it seems, and indeed the files in `glimpl` only build under cgo.

**Comment by hugelgupf** [comment]
Here's a question for you, btw.

I found it curious that you made a new directory and created a new go.mod to get & build a binary. Do you often make ephemeral modules like that? Is that how you'd expect this to work, as well?

`go`'s main module go.mod is always the one of the directory you're in. `makebb` does *not* currently follow that behavior and tries to merge each commands' main module go.mod. I.e. it'd ignore the `more-tests/go.mod` you made and try to use `gioui.org/example/go.mod`. `makebb` tries to generate an ephemeral go.mod, rather than leaving that task to the user.

I'm totally unsure of this UI interaction, because I don't know how people usually use Go modules.

**Comment by hugelgupf** [comment]
Maybe I'll add a mode-switch to the tool to say "use the current directory's go.mod". Then we can debate which makes more sense as the default. I have a feeling following `go` will end up being better, the more I think about the behavior (and the fact that half of the [dependency conflict README](https://github.com/u-root/gobusybox#common-dependency-conflicts) comes from trying to generate one...)

**Comment by orangecms** [comment]
> I found it curious that you made a new directory and created a new go.mod to get & build a binary. Do you often make ephemeral modules like that? Is that how you'd expect this to work, as well?

Two things to this: There were some similar directories for testing within the project, and I like to scope things. So I followed along and created my directory within the project after cloning it. That said, I prefer to have some project directory, say, `~/Projects/` to separate project I work on. Golang was trying to force me to reflect the web on my file system, which is a thing I really don't like about it; when I first started, I cloned a repo, say, to `~/Projects/foo/`, then created something like `~/Projects/foo/src/github.com/user/` and symlinked the `foo` directory into it again, and set `GOPATH` accordingly, because I didn't understand it. That's where I'm coming from.

> `go`'s main module go.mod is always the one of the directory you're in. `makebb` does _not_ currently follow that behavior and tries to merge each commands' main module go.mod. I.e. it'd ignore the `more-tests/go.mod` you made and try to use the `go.mod` for `gioui.org/example`. `makebb` tries to generate an ephemeral go.mod, rather than leaving that task to the user.

Okay, that I didn't anticipate, thanks! :-)

> I'm totally unsure of this UI interaction, because I don't know how people usually use Go modules.

I guess I am not a good testbench here... I merely understand tiny bits of it. To be honest, I wish it was simpler. I'm much used to the Node.js / npm thing where you simply have a `node_modules/` directory right within your project directory, so it won't pollute or collide with anything outside and you can simply tar it up and push it wherever to continue working or just run an application. It may be a bias, but it's something I definitely miss in other languages/interpreters/runtimes.

That being said, I wanted to get back to https://github.com/orangecms/wsd-cuse at some point and continue. That's a simpler candidate for playing around with `makebb` since it has no dependencies (yet). It could help me learn about Go modules.

**Comment by orangecms** [comment]
Well, I just tried it, see #41 - now this is very confusing... :thinking:

**Comment by orangecms** [comment]
Another thought: I would find it reasonable that new Go developers probably follow https://golang.org/doc/code.html regarding module usage.

**Comment by hugelgupf** [comment]
> Another thought: I would find it reasonable that new Go developers probably follow https://golang.org/doc/code.html regarding module usage.

Thanks for that, I will take a closer look at that. I've read a lot about modules, but my experience is as little as yours with actual modules. Maybe I'll also use Twitter for this one :)
