### ISSUE TITLE
findpkg: if we drop support for Go 1.13, can this code be removed?

### ISSUE THREAD

**Issue by hugelgupf** [u-root/gobusybox#61]
If we drop support for Go 1.13, can this code be removed? 

There's a comment here I wrote a long time ago which refers to a section of code that only exists because of Go 1.13: [Lines 172-205](https://github.com/u-root/gobusybox/blob/fcf634c39c0ed91bde24d69134b7828582d5c030/src/pkg/bb/findpkg/bb.go#L172-L205)

However, this could still be useful because we emit [these skip notes](https://github.com/u-root/gobusybox/blob/fcf634c39c0ed91bde24d69134b7828582d5c030/src/pkg/bb/findpkg/bb.go#L203) as part of the build. 

If I remember correctly, when you look up a package that doesn't fit any build criteria through packages.Load on Go >=1.14, you'll get a similar error message. Maybe we can delete the code and emit a similar error message in those cases? I think this needs some experimentation.

(E.g. I don't think we want to turn those warnings into errors, which would happen if we _just_ delete the code.)

**Comment by MDr164** [comment]
To add to that, should we maybe bump the minimum Go version to something more recent like 1.16 instead of keeping 1.13 around or are there other reasons to still keep 1.13 as the minimum version?

**Comment by hugelgupf** [comment]
I typically don't bump the minimum version until I find something that makes the tests fail before version 1.x or whatever.

I see a tangible reason here: 1.13 is old and we could gain some simplification (maybe). I'd bump to 1.14. But I don't see a reason to exclude 1.14 yet other than "it's older than 1.15".

**Comment by MDr164** [comment]
Got it. Thanks for clarifying!

**Comment by hugelgupf** [comment]
Solved by #79.
